addons:
    apt:
        update: true

notifications:
    irc: "chat.freenode.net#pdudaemon"
    on_success: always
    on_failure: always
    use_notice: false
    skip_join: false

before_install:
    - sudo bash -c 'echo "deb http://01.archive.ubuntu.com/ubuntu/ xenial main restricted universe multiverse" >> /etc/apt/sources.list'
    - sudo apt-get update
    - sudo apt-get install -y pep8 python3-setuptools python3-pip libsystemd-dev curl psmisc

install:
    - pip3 install --upgrade pip
    - pip3 install --user -r requirements.txt
    - pip3 install --user pycodestyle

script:
    - pycodestyle --ignore=E501 .
    - sudo python3 ./setup.py install
    - ./share/pdudaemon-test.sh
