#! /usr/bin/python

#  Copyright 2013 Linaro Limited
#  Author Matt Hart <matthew.hart@linaro.org>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.

import logging
from lavapdu.shared import read_settings
from lavapdu.shared import get_common_argparser
from lavapdu.shared import setup_daemon
import lavapdu.runnermaster as runnermaster

from lavapdu.pdurunner import PDURunner


if __name__ == '__main__':
    pidfile = "/var/run/lavapdu-runner.pid"
    logfile = "/var/log/lavapdu-runner.log"
    conffile = "/etc/lavapdu/lavapdu.conf"

    parser = get_common_argparser(None, logfile)
    options = parser.parse_args()

    settings = read_settings(conffile)

    context = setup_daemon(options, settings, pidfile)
    with context:
        runnermaster.start_em_up(settings)
